### ISSUE TITLE
JS closure triggers "warning: function statements are not standard" messages

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#103]
This code
```
function sayHello(name) {
  if (name.length > 3) {
    var text = 'Hello ' + name;
    function sayAlert() { print(text); }
  } else {
    var text = 'Hi ' + name;
    function sayAlert() { print(text); }
  }
  sayAlert();
}

sayHello('Bob')
```
prints warnings:
```
closure-1.js:4: warning: function statements are not standard
closure-1.js:7: warning: function statements are not standard
Hi Bob
```

The code is JS closure that seems to be valid and widely discussed, see for example: https://stackoverflow.com/questions/111102/how-do-javascript-closures-work

Replacing ```function Xx``` with ```var Xx = function``` makes warnings to go away, so it only dislikes the ```function``` syntax.

**Comment by ccxvii** [comment]
That's because function statements are not part of the ECMAScript standard. They are very commonly implemented in other JS interpreters, so we also support them, but with a warning.
