### ISSUE TITLE
Error message of the exception thrown frtom the native function contains bad characters

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#109]
```
Error: something bad happened!
	at  (native)
	at [string]:25
```

**Comment by sgbeal** [comment]
That � symbol suggests that the input is not properly encoded. AFAIK (but i may be wrong), mujs expects input to be UTF8.

**Comment by yurivict** [comment]
This is thrown from the native code. The name of the function was in ASCII. What input is in question here?

**Comment by sgbeal** [comment]
The input script which triggered this. i'm just speculating, though.

**Comment by yurivict** [comment]
The script only throws "something bad happened!".

**Comment by ccxvii** [comment]
I can't do anything about this without an example.

**Comment by yurivict** [comment]
I'll post an example.

**Comment by ccxvii** [comment]
Closing due to lack of information.
