### ISSUE TITLE
Set type

### ISSUE THREAD

**Issue by cup** [ccxvii/mujs#110]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by sebras** [comment]
This as introduced in ECMAScript 6, and since mujs targets ECMAScript 5.1 it is unlikely mujs will implement this (any time soon). I'll let @ccxvii close the bug though since he has the final say.

**Comment by ccxvii** [comment]
Correct. If you need to add a Set type in MuJS, you can implement it yourself in either JS or using C bindings. This is not a feature we're going to add to the core mujs library, which targets ES5.1.
