### ISSUE TITLE
Small float literals being converted to zero

### ISSUE THREAD

**Issue by gardhr** [ccxvii/mujs#115]
var control = FLT_MIN, /* 1.175494351e-38 */
 sample = 1.175494351e-38
print("control:", control)
print("sample:", sample)
print("sample == control:", sample == control) 
print("sample == 0:", sample == 0) 

/*

control: 1.1754943508222876e-38
sample: 0
sample == control: false
sample == 0: true

*/

**Comment by gardhr** [comment]
This however does work: Number("1.175494351e-38")

**Comment by ccxvii** [comment]
This was a bug in the opcode generation. Thanks for spotting it!

Fixed in commit 6b522a0.
