### ISSUE TITLE
js_delregistry doesn't unregister the object class

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#116]
The following example fails in the constructor of the unregistered object:
```
Error: Failing in constructor
```

It should fail as if the class Yyy has never been registered:
```
ReferenceError: 'Yyy' is not defined
```

```
#include <mujs.h>

const char *Tag = "Yyy";

void fnConstr(js_State *J) {
        js_newerror(J, "Failing in constructor");
        js_throw(J);
}

int main() {
        js_State *J = js_newstate(0, 0, 0);

        // register
        js_newobject(J);
        js_setregistry(J, Tag);
        js_pushglobal(J);
        js_getregistry(J, Tag);
        js_newcconstructor(J, fnConstr, fnConstr, Tag, 0);
        js_defproperty(J, -2, Tag, JS_DONTENUM);
        js_pop(J, 1);

        // unregister
        js_delregistry(J, Tag);

        // run
        js_dostring(J, "new Yyy");

        // cleanup
        js_gc(J, 0);
        js_freestate(J);
}
```

**Comment by isRyven** [comment]
Um, no? You clearly stored your constructor under the `Tag` name in global object, deleting your prototype object from registry does change absolutely nothing, registry is there just to be some sort of hidden value storage, which keeps values from being collected, deleting anything from registry doesn't remove this automatically from the other places. Your example code makes zero sense as well, so i guess you have just misunderstood some concepts here.

**Comment by ccxvii** [comment]
The documentation for the registry says: "The registry can be used to store references to Javascript objects accessible from C, but hidden from Javascript to prevent tampering."

I don't know what makes you think this means that objects put in the registry will be accessible from Javascript.

I'm afraid I also have no idea what your code example wants to accomplish. If you remove the invisible from JS stashing and removing the object from the registry, it's creating a function and assigning that to "global.Xxx" and then calling it. Sounds like your output is exactly what is supposed to happen based on your code.
