### ISSUE TITLE
Negative numbers converted to positive integers

### ISSUE THREAD

**Issue by gardhr** [ccxvii/mujs#124]
Example:

var val = -1
print("val:", val) 

Output: 

val: 4294967295

The fact that it returns 2^32 - 1 makes me wonder because I've redefined jsInstruction to long. Maybe that's the problem?

**Comment by isRyven** [comment]
Yeah wrong instruction type usually leads to the problem, i had same issue when i defined it as `unsigned int`, but setting it to just `int` did the trick.

**Comment by gardhr** [comment]
Looks like it just needs to be a signed number. Changed it from "unsigned long" to "long" and everything works just fine now.

**Comment by gardhr** [comment]
PEBCAK
