### ISSUE TITLE
let is not support ??

### ISSUE THREAD

**Issue by 756445638** [ccxvii/mujs#138]
[yuyang@localhost release]$ ./mujs  -i
> let a = 1;
SyntaxError: [stdin]:1: unexpected token: (identifier) (expected ';')
>

**Comment by ccxvii** [comment]
"let" is not part of ECMAScript 5 language. The "let" and "const" keywords were added in a later version of the language, which is not supported by mujs.

**Comment by 756445638** [comment]
ok thanks
