### ISSUE TITLE
Get rid of setjmp

### ISSUE THREAD

**Issue by trufae** [ccxvii/mujs#170]
Despite being a useful function and simplifies a lot the error handling it reduces portability and performance and causes issues when combined with threads, qjs is the only js runtime out there that it's not using it (even lua or duktape use setjmp 😱) but i find mujs super clean and simple and i wished  about this, any thoughs on this?

**Comment by ccxvii** [comment]
It won't happen without a complete rewrite. The use of setjmp for error handling (and garbage collection for cleanup) is very pervasive throughout the code.
