### ISSUE TITLE
Hardcoded shared library path [/usr/lib64/libmujs.so] ?

### ISSUE THREAD

**Issue by VielLosero** [ccxvii/mujs#192]
Important Information

- mpv version: 0.38.0
- Platform version: slackware 15.0
- Meson version: meson-0.59.4

[root@arcadia test1]# mpv --version
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec 24 2024 03:24:30
libplacebo version: v7.349.0
FFmpeg version: 4.4.5
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100

Reproduction Steps

Install mpv with "sbopkg -i mpv" from slackbuilds on slackware 15.0
meson
--prefix=/usr
--libdir=/usr/lib${LIBDIRSUFFIX}
--sysconfdir=/etc
--mandir=/usr/man
-Dbuildtype=release
-Dmanpage-build=enabled
-Djavascript=disabled
-Dlibmpv=true
-Dhtml-build=enabled
-Dcdda=enabled
-Ddvdnav=enabled
-Ddvbin=enabled
$pipewire
$BUILD_OPTS
. build
Expected Behavior

[root@arcadia test]# readelf -d usr/bin/mpv |head -20

Dynamic section at offset 0x245990 contains 70 entries:
Tag Type Name/Value
0x0000000000000001 (NEEDED) Shared library: [libdl.so.2]
0x0000000000000001 (NEEDED) Shared library: [libass.so.9]
0x0000000000000001 (NEEDED) Shared library: [libavcodec.so.58]
0x0000000000000001 (NEEDED) Shared library: [libavfilter.so.7]
0x0000000000000001 (NEEDED) Shared library: [libavformat.so.58]
0x0000000000000001 (NEEDED) Shared library: [libavutil.so.56]
0x0000000000000001 (NEEDED) Shared library: [libplacebo.so.349]
0x0000000000000001 (NEEDED) Shared library: [libswresample.so.3]
0x0000000000000001 (NEEDED) Shared library: [libswscale.so.5]
0x0000000000000001 (NEEDED) Shared library: [libcdio_paranoia.so.2]
0x0000000000000001 (NEEDED) Shared library: [libcdio_cdda.so.2]
0x0000000000000001 (NEEDED) Shared library: [libcdio.so.19]
0x0000000000000001 (NEEDED) Shared library: [libm.so.6]
0x0000000000000001 (NEEDED) Shared library: [libdvdnav.so.4]
0x0000000000000001 (NEEDED) Shared library: [libpthread.so.0]
0x0000000000000001 (NEEDED) Shared library: [libmujs.so] <----
0x0000000000000001 (NEEDED) Shared library: [liblcms2.so.2]
Actual Behavior

[root@arcadia test]# readelf -d usr/bin/mpv |head -20

Dynamic section at offset 0x245990 contains 70 entries:
Tag Type Name/Value
0x0000000000000001 (NEEDED) Shared library: [libdl.so.2]
0x0000000000000001 (NEEDED) Shared library: [libass.so.9]
0x0000000000000001 (NEEDED) Shared library: [libavcodec.so.58]
0x0000000000000001 (NEEDED) Shared library: [libavfilter.so.7]
0x0000000000000001 (NEEDED) Shared library: [libavformat.so.58]
0x0000000000000001 (NEEDED) Shared library: [libavutil.so.56]
0x0000000000000001 (NEEDED) Shared library: [libplacebo.so.349]
0x0000000000000001 (NEEDED) Shared library: [libswresample.so.3]
0x0000000000000001 (NEEDED) Shared library: [libswscale.so.5]
0x0000000000000001 (NEEDED) Shared library: [libcdio_paranoia.so.2]
0x0000000000000001 (NEEDED) Shared library: [libcdio_cdda.so.2]
0x0000000000000001 (NEEDED) Shared library: [libcdio.so.19]
0x0000000000000001 (NEEDED) Shared library: [libm.so.6]
0x0000000000000001 (NEEDED) Shared library: [libdvdnav.so.4]
0x0000000000000001 (NEEDED) Shared library: [libpthread.so.0]
0x0000000000000001 (NEEDED) Shared library: [/usr/lib64/libmujs.so] <----
0x0000000000000001 (NEEDED) Shared library: [liblcms2.so.2]

You can see how meson links the libraries in the log:

[281/283] cc -o mpv [...] -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -Wl,-z,noexecstack -rdynamic -O2 -fPIC -Wl,--start-group -ldl [...] /usr/lib64/libmujs.so [...] -Wl,--end-group

I can't figure out why, but this seems to be an oddity with mujs that I can reproduce on my Arch system:

% echo "int main() { return 0; }" >x.c
% gcc x.c -o x /usr/lib/libmujs.so 
% readelf -d x | grep \.so
 0x0000000000000001 (NEEDED)             Shared library: [/usr/lib/libmujs.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
% gcc x.c -o x /usr/lib/libavcodec.so
% readelf -d x | grep \.so           
 0x0000000000000001 (NEEDED)             Shared library: [libavcodec.so.61]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

Either way nothing to do with mpv.

**Comment by VielLosero** [comment]
Maybe I'm wrong, but if it's a static library, why does it appear in the dynamic library ELF ?
I am looking deeper.

**Comment by 13ilya** [comment]
I don't know how mpv is built in Slackware, in openSUSE mujs is not in shared libraries and JS scripts work.
```
LC_ALL=en readelf -d /usr/bin/mpv

Dynamic section at offset 0x3130d0 contains 78 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libass.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libavcodec.so.61]
 0x0000000000000001 (NEEDED)             Shared library: [libavfilter.so.10]
 0x0000000000000001 (NEEDED)             Shared library: [libavformat.so.61]
 0x0000000000000001 (NEEDED)             Shared library: [libavutil.so.59]
 0x0000000000000001 (NEEDED)             Shared library: [libplacebo.so.349]
 0x0000000000000001 (NEEDED)             Shared library: [libswresample.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libswscale.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_paranoia.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_cdda.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio.so.19]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdvdnav.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [liblcms2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libarchive.so.13]
 0x0000000000000001 (NEEDED)             Shared library: [libavdevice.so.61]
 0x0000000000000001 (NEEDED)             Shared library: [libbluray.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [liblua5.1.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [librubberband.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libuchardet.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libvapoursynth-script.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libzimg.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libjack.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libopenal.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpipewire-0.3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpulse.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcaca.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgbm.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libjpeg.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libsixel.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-client.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-cursor.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libxkbcommon.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXss.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXpresent.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXrandr.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXv.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libEGL.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-egl.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libvulkan.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libva-drm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libva.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libva-wayland.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libva-x11.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libvdpau.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x52000
 0x000000000000000d (FINI)               0x1e4dc4
 0x0000000000000019 (INIT_ARRAY)         0x2cd1f0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x2cd1f8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x3c0
 0x000000006ffffef5 (GNU_HASH)           0x2e40
 0x0000000000000005 (STRTAB)             0xd700
 0x0000000000000006 (SYMTAB)             0x38d8
 0x000000000000000a (STRSZ)              30802 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x3135f0
 0x0000000000000002 (PLTRELSZ)           31896 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x49510
 0x0000000000000007 (RELA)               0x15fd0
 0x0000000000000008 (RELASZ)             210240 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW PIE
 0x000000006ffffffe (VERNEED)            0x15c80
 0x000000006fffffff (VERNEEDNUM)         17
 0x000000006ffffff0 (VERSYM)             0x14f52
 0x000000006ffffff9 (RELACOUNT)          8679
 0x0000000000000000 (NULL)               0x0
```

**Comment by avih** [comment]
There's both static and dynamic libs, and by default both are built (and installed).

Which one gets linked depends on the build system and the flags used for linkage.

Typically the dynamic lib (.so) is linked.

**Comment by 13ilya** [comment]
> There's both static and dynamic libs, and by default both are built (and installed).

I have only a static library built by default.
How do I build a shared library?

https://build.opensuse.org/package/live_build_log/devel:languages:javascript/mujs/openSUSE_Tumbleweed/x86_64
```
[   21s] + make install DESTDIR=/home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64 prefix=/usr libdir=/usr/lib64 'CFLAGS=-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC'
[   21s] cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC -O3 -c -o build/release/libmujs.o one.c
[   27s] cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC -O3 -o build/release/mujs main.c build/release/libmujs.o -lm -DHAVE_READLINE -lreadline
[   30s] cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -g -fPIC -O3 -o build/release/mujs-pp pp.c build/release/libmujs.o -lm
[   33s] echo > build/release/mujs.pc Name: mujs
[   33s] echo >> build/release/mujs.pc Description: MuJS embeddable Javascript interpreter
[   33s] echo >> build/release/mujs.pc Version: 1.3.5
[   33s] echo >> build/release/mujs.pc Cflags: -I/usr/include
[   33s] echo >> build/release/mujs.pc Libs: -L/usr/lib64 -lmujs
[   33s] echo >> build/release/mujs.pc Libs.private: -lm
[   33s] install -d /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/include
[   33s] install -d /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/lib64
[   33s] install -d /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/lib64/pkgconfig
[   33s] install -d /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/bin
[   33s] install -m 644 mujs.h /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/include
[   33s] install -m 644 build/release/mujs.pc /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/lib64/pkgconfig
[   33s] install -m 755 build/release/mujs /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/bin
[   33s] install -m 755 build/release/mujs-pp /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/bin
[   33s] ar cr build/release/libmujs.a build/release/libmujs.o
[   33s] install -m 644 build/release/libmujs.a /home/abuild/rpmbuild/BUILDROOT/mujs-1.3.5-27.1.x86_64/usr/lib64
```

**Comment by avih** [comment]
> > There's both static and dynamic libs, and by default both are built (and installed).
> 
> I have only a static library built by default.

Well, both are built by default for `make release` (check build/release), but `make install` does `make install-static`, which indeed installs only the static lib.

`make install-shared` will install the shared lib.

**Comment by VielLosero** [comment]
Thanks for explanation. I will try.

**Comment by 13ilya** [comment]
> `make install-shared` will install the shared lib.

```
W: no-soname /usr/lib64/libmujs.so
The library has no soname.
```
It is certainly there, but it is not assembled correctly without soname and it is not possible to link with it normally.
