### ISSUE TITLE
Embedded builds?

### ISSUE THREAD

**Issue by beriberikix** [ccxvii/mujs#22]
Are there any plans to create builds specifically targeted at running on embedded systems? Something like [Espruino](https://github.com/espruino/Espruino) or [micropython](http://micropython.org/) come to mind.

**Comment by ccxvii** [comment]
Are you having any particular problems building it for your embedded system of choice?

**Comment by beriberikix** [comment]
I haven't just yet but I do have an M0 and two M4 boards I'd like to play around with running something other than Lua. Since this is an interpreter, some sort of bootloader/rtos is needed to run this, correct? Access to hardware via HALs, managing processes, etc. My main question is if this is something you're planning on exploring or if others have expressed interest.

Thanks!
