### ISSUE TITLE
Bind throws TypeError : 'prototype' is read-only

### ISSUE THREAD

**Issue by hbp** [ccxvii/mujs#27]
function F (a,b,c) { print (a,b,c) }; var Fa = F.bind (null, 123);
TypeError: 'prototype' is read-only
	[C]: in function 'bind'
	[string]:1: in function ''
	[C]: in function '?'

**Comment by ccxvii** [comment]
Fixed in 5aed7d6e94028464e7fefffef407c28e42082d8b.
