### ISSUE TITLE
Function property issue

### ISSUE THREAD

**Issue by hbp** [ccxvii/mujs#30]
mujs:
```
> function myFunction (a,b,c) { return [a,b,c] };
> typeof myFunction
function
> typeof myFunction.name
undefined
> Object.getOwnPropertyNames (myFunction)
length,prototype
```
Chromium :
```
function myFunction (a, b, c) { return [a,b,c] }
myFunction(a, b, c) { return [a,b,c] }
Object.getOwnPropertyNames (myFunction)
["length", "name", "arguments", "caller", "prototype"]

```
So the function properties `name`, `arguments` and `caller` are are not implemented.

**Comment by ccxvii** [comment]
The function properties 'arguments' and 'caller' are deprecated and not allowed at all in strict mode. The property 'name' is not part of the language specification (though implemented by many interpreters).

**Comment by hbp** [comment]
Ok, I agree. But `name` would be nice to have ;-)
