### ISSUE TITLE
Problem using library from C++

### ISSUE THREAD

**Issue by njlr** [ccxvii/mujs#36]
I can include MuJS as follows: 

```
extern "C" {
  #include <mujs.h>
}
```

But then I get the error: 

> ccxvii/mujs/1.11.0/mujs.h:150:106: error: expected ')'
void js_newuserdatax(js_State *J, const char *tag, void *data, js_HasProperty has, js_Put put, js_Delete delete, js_Finalize finalize);

Renaming `delete` to `d` solves the issue. 

Perhaps this change should be integrated in the library for C++ users?

**Comment by ccxvii** [comment]
Fixed.
