### ISSUE TITLE
How to optimize MuJS for speed

### ISSUE THREAD

**Issue by AsierRF** [ccxvii/mujs#43]
Hello,

I would like to ask if there exists any compiling flag or setup that makes MuJS be optimised for speed. This possibility is mentioned on the main web page for MuJS https://mujs.com/

Thanks.

Kind regards,
Asier Rivera.

**Comment by avih** [comment]
You can add to `-O2` or `-O3` to `CFLAGS` at `Makefile`. Depending on your compiler, you might see up to 20-40% speedup.

**Comment by ccxvii** [comment]
As avih mentioned, you can change the compiler flags. Compiling MuJS is as simple as "gcc -O3 -c one.c -o libmujs.o".
