### ISSUE TITLE
how to call a have variable argument lists c language function 

### ISSUE THREAD

**Issue by zengming00** [ccxvii/mujs#47]
how to call a have variable argument lists c language function , i want call like 'printf(fmt,...)' function from javascript, how to implement

**Comment by ccxvii** [comment]
Use the js_gettop() function to see how many arguments are on the stack. See the implementation of Math.min (which is a varargs function) in jsmath.c, or the jsB_print function in main.c.

**Comment by zengming00** [comment]
that is not what I want

**Comment by ccxvii** [comment]
You asked how to use variable argument lists. I pointed you to two examples that use variable argument lists. I don't know what else you want.
