### ISSUE TITLE
UTF-16 Source Code Cannot be Recognized

### ISSUE THREAD

**Issue by JitCompiler** [ccxvii/mujs#52]
Javascript source code should be in unicode characters. But when I tried to compile the source file in UTF16 format (either big endian or little endian) , it complaint about syntax error when it read the first byte of the source file (which contains the 0xFEFF Byte Order Mark).

Does mujs support unicode at all? In particular, how should I code text strings having unicode characters?

**Comment by ccxvii** [comment]
MuJS currently only supports UTF-8 encoded source text. UTF-16 is an abomination and should be avoided, IMO :)

Either use UTF-8, or use ASCII and escape sequences to encode unicode characters in strings: "\u00A9".
