### ISSUE TITLE
Missing Lower Case Character Range

### ISSUE THREAD

**Issue by JitCompiler** [ccxvii/mujs#53]
In some random tests, I found that the character U+02aa is not recognized as a valid identifier character.

```
var \u02aa="s";
\u02aa + "3";

SyntaxError: mujs\testjs.js:2: unexpected character: \u02AA

```
But U+02aa is listed as Lowercase character here:

[http://www.fileformat.info/info/unicode/category/Ll/list.htm](http://www.fileformat.info/info/unicode/category/Ll/list.htm)

fyi, javascript identifiers can consist of characters from these categories: Uppercase letter, Lowercase letter, Titlecase letter, and some more. I am not able to comprehend the various tables used in `utftype.c`, but it looks like the lower case ranges in this source file are incomplete.

Note that it is possible for Javascript obfuscators to turn an ordinary long ASCII identifier to a single 16bit unicode character.  So it is very possible that identifiers may contain odd characters like \u02aa.

**Comment by ccxvii** [comment]
Fixed in the commit that adds new unicode character data tables.
