### ISSUE TITLE
Date.now() lacks milliseconds on Mac

### ISSUE THREAD

**Issue by SteveJobzniak** [ccxvii/mujs#56]
Timer resolution on Macs is always "000". Maybe this line is the culprit:

https://github.com/ccxvii/mujs/blob/41625ec2d007c65bb39e89d4b4a49236a16be558/jsdate.c#L25-L27

Result:

```
$ mujs
> Date.now()
1512947603000
> Date.now()
1512947607000
> Date.now()
1512947608000
> Date.now()
1512947608000
> Date.now()
1512947609000
> Date.now()
1512947610000
> Date.now()
1512947610000
> Date.now()
1512947610000
> Date.now()
1512947611000
```

**Comment by ccxvii** [comment]
I would have expected MacOSX to set the __unix__ macro, so that we can use gettimeofday() but I guess not...

**Comment by SteveJobzniak** [comment]
Yeah, it should probably set that macro since macOS is based on FreeBSD... Hmm, but the results indicate that it's not doing that. Since the output is using the "`* 1000`" fallback...

I did see that macOS has `gettimeofday()` so hopefully it's just a matter of using another macro to detect Macs.

**Comment by avih** [comment]
It's also possible, if less likely, that `gettimeofday` returns in seconds resolution.

**Comment by SteveJobzniak** [comment]
That's probably not it...

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/gettimeofday.2.html

The time is expressed in seconds and
     microseconds since midnight (0 hour), January 1, 1970.

**Comment by SteveJobzniak** [comment]
@ccxvii Not sure if true, but `wm4: __unix__ sounds like something non-standard` (he's the main dev of `mpv` so if he says that he doesn't know what it is then it is probably something non-standard) ;-)

**Comment by ccxvii** [comment]
The `__unix__` macro catches all the main Linux and BSD variants. Adding a check for `__APPLE__` should do the trick. Let me know if it doesn't work.

**Comment by SteveJobzniak** [comment]
@ccxvii Thanks, I wrote a small test:

```c
#include <stdio.h>
#include <math.h>
#include <sys/time.h>

int main()
{
    printf("Hello World\n");
#if defined(__unix__)
    printf("unix\n");
#endif
#if defined(__APPLE__)
    printf("apple\n");
#endif

    struct timeval tv;
	gettimeofday(&tv, NULL);
	double tx = floor(tv.tv_sec * 1000.0 + tv.tv_usec / 1000.0);
    printf("%.f\n", tx);
}
```

Result on a Mac:

```
+ $ ./a.out 
Hello World
apple
1512999085793

+ $ ./a.out 
Hello World
apple
1512999086631

+ $ ./a.out 
Hello World
apple
1512999087257
```

Thank you. That concludes that the new version will work.

Could you please consider tagging v1.0.2 so that distros pick it up with all these array sort and Mac fixes? <3
