### ISSUE TITLE
Please tag v1.0.2

### ISSUE THREAD

**Issue by SteveJobzniak** [ccxvii/mujs#57]
Hi @ccxvii, thanks again for the quick solving of the two bugs I reported yesterday. Incredible work.

Would you please mind tagging v1.0.2 so that distributions will pick it up and start building it? It has a fixed ton of bugs over v1.0.1. 👍 

Thanks for your hard work.

**Comment by ccxvii** [comment]
Done.

**Comment by SteveJobzniak** [comment]
Thank you. 👍  ❤️
