### ISSUE TITLE
localeCompare with sensitivity flag

### ISSUE THREAD

**Issue by SteveJobzniak** [ccxvii/mujs#58]
Just a small note on standards compliance... not sure if anyone even uses this function.

```
$ mujs
> var a = 'ab';
> var b = 'Ab';
> a.localeCompare(b, 'en', {'sensitivity': 'base'});
32
> b = 'ab';
ab
> a.localeCompare(b, 'en', {'sensitivity': 'base'});
0
> a = 'Ab';
Ab
> a.localeCompare(b, 'en', {'sensitivity': 'base'});
-32
```

Expected result:

All three should return `0`, since they are meant to be equal when case-sensitivity is `base`.

**Comment by ccxvii** [comment]
localeCompare only takes one argument in ECMAScript 5.

The locale and options arguments are new additions in ES2015 (which is a completely separate language which MuJS does not implement).

**Comment by SteveJobzniak** [comment]
Sorry, I thought I checked the ES5.1 spec - but you're right, it's not in ES5. Closing. ;-)
