### ISSUE TITLE
Setting array.length should delete old entries?

### ISSUE THREAD

**Issue by SteveJobzniak** [ccxvii/mujs#59]
Hi, I'm reading the following:

https://github.com/ccxvii/mujs/blob/2cb57c6e7188a8438c58e1e3fc452b7ad06bee33/jsarray.c#L14-L18

It seems to only set the length property. It doesn't actually delete the indexes. Is that correct? Many people use `arr.length = 0` to erase everything in an array but the MuJS code doesn't seem to have that effect.

Unlike `Array.splice()`, from the same file, which calls "delindex" on every index.

Here's what the spec says:

http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.5.2

> The length property of this Array object is a data property whose value is always numerically greater than the name of every deletable property whose name is an array index.

> The length property initially has the attributes `{ [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: false }`.

> NOTE Attempting to set the length property of an Array object to a value that is numerically less than or equal to the largest numeric property name of an existing array indexed non-deletable property of the array will result in the length being set to a numeric value that is one greater than that largest numeric property name. See 15.4.5.1.

**Comment by ccxvii** [comment]
js_setlength is only a shorthand for pushing and setting the 'length' property. If you look at the guts of jsR_setproperty in jsrun.c where the actual property setting is handled, you can see how we special case setting the 'length' property of Array class objects.

**Comment by SteveJobzniak** [comment]
@ccxvii Oh, great to see that you're handling it there! Thanks. :-)
