### ISSUE TITLE
Websocket implementation

### ISSUE THREAD

**Issue by betaredex** [ccxvii/mujs#60]
So I was writing a plugin for [mpv](https://github.com/mpv-player/mpv), and I want to be able to connect to a websocket in the JavaScript. Does MuJS have a websocket implementation? As far as I can tell, the w3c implementation doesn't work, and I neither did browserify-ing some npm modules. Help would be appreciated.

**Comment by avih** [comment]
mujs is an embedded js engine, not a web backend. As such, scripts which it runs can only communicate with the system/anything via the APIs which the embedding code provides. At the case of mpv, that's via the functions of `mp.utils`.

**Comment by betaredex** [comment]
Alright, thank you. I'll bring this over to the mpv folks then.
