### ISSUE TITLE
Please fix clang compiler warnings: generic selections are a C11-specific feature

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#64]
There are many warnings like this:
```
In file included from one.c:23:
./jsvalue.c:25:7: warning: generic selections are a C11-specific feature [-Wc11-extensions]
        if (!isfinite(n) || n == 0)
             ^
```

**Comment by ccxvii** [comment]
That looks like a bug/problem with your system headers. "isfinite" is a standard macro from "math.h". MuJS uses the system macro, it doesn't define its own version, and certainly does not use the _Generic macro.

**Comment by yurivict** [comment]
You are right. "isfinite" expansion is C11 on my system. This doesn't normally trigger warnings, but ```-pedantic``` makes it to. This is a minor thing, anyways.

Closing, thanks!
