### ISSUE TITLE
Please provide an example how to bind a user-defined object to the JS object

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#75]
I need to return to the JS script the user-defined pointer. It needs to be retrievable by subsequent calls where it is passed as an argument, and be destructable.

I was looking for something like this:
```
void js_pushuserdatax(js_State *J, void *data, js_HasProperty has, js_Put put, js_Delete del, js_Finalize finalize);
```
but it isn't in the version 1.0.5

**Comment by ccxvii** [comment]
See js_newuserdata or js_newuserdatax.

**Comment by ccxvii** [comment]
If you want some more example code to look at, you can look at the MuJS bindings in MuPDF:

http://git.ghostscript.com/?p=mupdf.git;a=blob;f=source/tools/murun.c

**Comment by yurivict** [comment]
Thank you for the use examples!
