### ISSUE TITLE
The finalize function for user objects is called multiple times

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#80]
I attach my objects to JS objects. I added printouts into a regular and copy constructors, and the destructor. The log shows that the destructor is called multiple times. The destructor is called from the finalize method.

```
MyObject::MyObject(copy) 0x801c4b000
MyObject::~MyObject 0x801c4b000
MyObject::MyObject(copy) 0x801c4b000
MyObject::MyObject(copy) 0x801c4bc30
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801c4cd10
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801c4ddf0
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801c4eed0
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801c4ffb0
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801cab090
MyObject::MyObject() 0x7fffffffdde8
MyObject::~MyObject 0x7fffffffdde8
MyObject::MyObject(copy) 0x801cac170
MyObject::MyObject(copy) 0x801cac7b0
MyObject::MyObject(copy) 0x801cacc60
MyObject::MyObject() 0x801cad0c0
MyObject::MyObject() 0x7fffffffe2f8
MyObject::~MyObject 0x7fffffffe2f8
MyObject::MyObject() 0x7fffffffe2f8
MyObject::~MyObject 0x7fffffffe2f8
MyObject::MyObject() 0x7fffffffe2f8
MyObject::~MyObject 0x7fffffffe2f8
MyObject::~MyObject 0x801cad0c0
MyObject::~MyObject 0x801cad0c0
MyObject::~MyObject 0x801cad0c0
MyObject::~MyObject 0x801cad0c0
MyObject::~MyObject 0x801cacc60
MyObject::~MyObject 0x801cac7b0
MyObject::~MyObject 0x801cac170
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801cab090
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801c4ffb0
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801c4eed0
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801c4ddf0
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801c4cd10
MyObject::~MyObject 0x801c4b000
MyObject::~MyObject 0x801c4bc30
MyObject::~MyObject 0x801c4b000
```

The process was also crashing, and valgrind kept printing errors in destructor called from the finalize function.

**Comment by gardhr** [comment]
I would not recommend doing that. The C setjmp/longjmp facilities used by to the library can cross C++ destuctor and exception boundaries which in turn can lead to serious program stability issues. So first try compiling to obj/lib/dll format which can safely be called from C++ ABI.

**Comment by yurivict** [comment]
@gardhr This consideration is irrelevant. C++ destructors shouldn't throw exceptions, the code that allows this is ill-behaved. Even if some code called from 'finalize' does throw an exception, it should be caught still inside 'finalize', and this way it would never cross any boundaries.

**Comment by ccxvii** [comment]
The finalizers have always worked for me.

You will need to provide a complete example if you want me (or anyone else) to take a deeper look at this.

**Comment by yurivict** [comment]
Testcase:

1. Clone this project: https://github.com/yurivict/ChemWiz
2. Build it: ```make USE_DSRPDB=no```
3. Run the test: ```./chemwiz test.js```
4. Observe the messages: ```ERROR bogus molecule in moleculeFinalize: 0x801a8f000 (duplicate finalize invocation)```

The messages are because the finalize function is called multiple times.
This is caught by the checking code here https://github.com/yurivict/ChemWiz/blob/master/js-binding.cpp#L44

**Comment by yurivict** [comment]
The problem was in my code, not in MuJS. Thanks to cebras for finding it!
