### ISSUE TITLE
[question] How to make one user object type a subclass of the other user object type?

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#82]
I would like to make all superclass methods to be available to subclass objects. For example, if the type P is a parent of the type C, the object of the type C should have the method pmeth() which is defined in the type P.

The things I tried:
* to assign prototypes: ```C.prototype = P.prototype```. This failed with the message saying that ```C.prototype``` is read-only.
* enumerate all keys in P and assign all functions to C:
```
for (var i = 0; i < P.prototype.keys(); i++) {
  var key = P.prototype.keys()[i]
  C.prototype[key] = P.prototype[key]
}
```
This also failed because there is no ```keys()``` function.

Objects have the flag ```extensible```, and there's also the ```preventExtensions()``` function.

But what is the correct way to add the extension relationship between objects?

**Comment by ccxvii** [comment]
Assigning the prototype property of a function works as it should. If this doesn't work for you, a full example would be helpful in tracking down the issue.

Setting up subclassing with Javascript's prototype system can be a bit un-intuitive. Here's one way to do it:

```
function P() { /* parent constructor */ }
P.prototype.pmeth = function () { print("pmeth"); }

function C() { /* child constructor */ }
C.prototype = Object.create(P.prototype); /* create 'inherited' prototype object */
C.prototype.cmeth = function () { print("cmeth"); }
```

The keys function is a method of the Object object: `var keys = Object.keys(obj)`. Note that it only returns the objects own properties, not those inherited from the prototype chain.
