### ISSUE TITLE
[improvement suggestion] Please make JS_ENVLIMIT a build parameter

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#94]
With ```JS_ENVLIMIT=64```, a recursive function with 1 argument can call itself ~61 times, and a function with 6 arguements can call itself ~27 times.

It is easy to exceed these limitations in a real-world code.

I suggest that you add a build-time parameter, ex. ```envlimit=1024``` would change this value to ```1024```.

**Comment by ccxvii** [comment]
Are you confusing JS_ENVLIMIT with JS_STACKSIZE?

**Comment by yurivict** [comment]
> Are you confusing JS_ENVLIMIT with JS_STACKSIZE?

Possibly. I'm not quite sure what's the difference. Maybe both should be made build-time configurable.

**Comment by ccxvii** [comment]
All limits are now configurable at build time by setting preprocessor defines.
