### ISSUE TITLE
[improvement suggestion] The error message 'TypeError: called object is not a function' could tell what the location in the source code is

### ISSUE THREAD

**Issue by yurivict** [ccxvii/mujs#95]
Currently, this error message is printed:
```
TypeError: called object is not a function
```

You could add a short description of what the object is, for example:
```
TypeError: called object is not a function: the object is a string: "Hello worl ..."
```
Same with arrays, etc. Just say what the object type is, and maybe prints a few characters of description followed by ellipsis. This would make this error message much more useful for debugging.

**Comment by yurivict** [comment]
Same with ```TypeError: cannot convert undefined to object```.

**Comment by ccxvii** [comment]
The message was improved to include the type of the object that is not a function in commit ffe0ca7d7f47dc11d8912b11daa388e66be358bb.

The location is (and has always been) available in the error.stackTrace property. See main.c for the more verbose Error.prototype.toString method used in the command line shell.
